services:
  back:
    command: "make runprod"
    build: .
    container_name: fastapi
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PGPORT=${PGPORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: ${PG_HOST}
    hostname: ${PG_HOST}
#    env_file: docker.compose.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

volumes:
  postgres_data:
