services:
  test_back:
    command: "make test-ci"
    build: .
    container_name: test_back
    environment:
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpass
      - PG_HOST=psqlhost
      - PGPORT=5432
      - POSTGRES_DB=psqldb
      - SECRET_KEY=12345
    depends_on:
      test_postgres:
          condition: service_healthy

  test_postgres:
    image: postgres:latest
    container_name: test_psql
    hostname: psqlhost
    environment:
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpass
      - POSTGRES_DB=test_psqldb
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
