services:
  test_back:
    command: "make test-ci"
    build: .
    container_name: test_back
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PGPORT=${PGPORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      test_postgres:
          condition: service_healthy

  test_postgres:
    image: postgres:latest
    container_name: test_psql
    hostname: ${PG_HOST}
    environment:
      - POSTGRES_USER=test_${POSTGRES_USER}
      - POSTGRES_PASSWORD=test_${POSTGRES_PASSWORD}
      - POSTGRES_DB=test_${POSTGRES_DB}
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
