[project]
name = "guadelupe"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = [".", "src"]
asyncio_mode='auto'
addopts = [
    "--import-mode=importlib",
]

[tool.mypy]
mypy_path = "src"
explicit_package_bases = "True"
ignore_missing_imports = "True"
