"""password length

Revision ID: 214a6d435331
Revises: be7b158105da
Create Date: 2024-03-27 14:40:15.746040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "214a6d435331"
down_revision: Union[str, None] = "be7b158105da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts_image", sa.Column("image_path", sa.String(), nullable=False))
    op.alter_column(
        "users_user",
        "password",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=80),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_user",
        "password",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    op.drop_column("posts_image", "image_path")
    # ### end Alembic commands ###
